/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.Catagory;
import dao.DaoCatagory;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public final class CatagoryView extends javax.swing.JFrame {

    DaoCatagory daoCatagoy = new DaoCatagory();
    Catagory cat;

    /**
     * Creates new form CatagoryView
     */
    public CatagoryView() {
        initComponents();
        clear();
        showAllData();
    }

    void clear() {
        txtCatagoryId.setText(" ");
        txtCatagoryName.setText(" ");

    }

    private void showAllData() {
        String[] colums = {"ID", "Name"};

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(colums);
        tblCatagoryView.setModel(model);

        List<Catagory> list =daoCatagoy.findAll() ;

        for (Catagory c : list) {
            model.addRow(new Object[]{
                c.getId(),
                c.getName()
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCatagoryName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCatagoryId = new javax.swing.JTextField();
        btnCatagorySave = new javax.swing.JButton();
        btnCatagoryUpdate = new javax.swing.JButton();
        btnCatagoryDelete = new javax.swing.JButton();
        btnCatagoryReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCatagoryView = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setBackground(new java.awt.Color(102, 102, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Catagory");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setText("Name :");

        jLabel2.setText("ID :");

        txtCatagoryId.setEditable(false);

        btnCatagorySave.setText("Save");
        btnCatagorySave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCatagorySaveMouseClicked(evt);
            }
        });
        btnCatagorySave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatagorySaveActionPerformed(evt);
            }
        });

        btnCatagoryUpdate.setText("Update");
        btnCatagoryUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCatagoryUpdateMouseClicked(evt);
            }
        });
        btnCatagoryUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatagoryUpdateActionPerformed(evt);
            }
        });

        btnCatagoryDelete.setText("Delete");
        btnCatagoryDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCatagoryDeleteMouseClicked(evt);
            }
        });

        btnCatagoryReset.setText("Reset");
        btnCatagoryReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatagoryResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCatagoryId, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnCatagorySave)
                        .addGap(111, 111, 111)
                        .addComponent(btnCatagoryUpdate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCatagoryDelete)
                        .addGap(95, 95, 95)
                        .addComponent(btnCatagoryReset)
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addComponent(txtCatagoryName))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCatagoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCatagoryId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCatagorySave)
                    .addComponent(btnCatagoryUpdate)
                    .addComponent(btnCatagoryDelete)
                    .addComponent(btnCatagoryReset))
                .addGap(18, 18, 18))
        );

        tblCatagoryView.setBackground(new java.awt.Color(204, 204, 255));
        tblCatagoryView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCatagoryView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCatagoryViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCatagoryView);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCatagorySaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatagorySaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatagorySaveActionPerformed

    private void btnCatagoryUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatagoryUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatagoryUpdateActionPerformed

    private void btnCatagoryResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatagoryResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatagoryResetActionPerformed

    private void btnCatagorySaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatagorySaveMouseClicked
        // TODO add your handling code here:

        cat = new Catagory(
                txtCatagoryName.getText().trim()
        );
        daoCatagoy.save(cat);
        clear();
        showAllData();
    }//GEN-LAST:event_btnCatagorySaveMouseClicked

    private void btnCatagoryUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatagoryUpdateMouseClicked
        // TODO add your handling code here:
        int id=Integer.parseInt(txtCatagoryId.getText());
        String name=txtCatagoryName.getText();
        
        Catagory c=new Catagory(id, name);
        daoCatagoy.update(c);
        clear();
        showAllData();
    }//GEN-LAST:event_btnCatagoryUpdateMouseClicked

    private void tblCatagoryViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCatagoryViewMouseClicked
        // TODO add your handling code here:
        int rowIndex=tblCatagoryView.getSelectedRow();
        String id=tblCatagoryView.getModel().getValueAt(rowIndex, 0).toString();
        String name=tblCatagoryView.getModel().getValueAt(rowIndex, 1).toString();
        
        txtCatagoryId.setText(id);
        txtCatagoryName.setText(name);
    }//GEN-LAST:event_tblCatagoryViewMouseClicked

    private void btnCatagoryDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatagoryDeleteMouseClicked
        // TODO add your handling code here:
        
        int id=Integer.parseInt(txtCatagoryId.getText());
        daoCatagoy.delete(id);
        clear();
        showAllData();
    }//GEN-LAST:event_btnCatagoryDeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatagoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatagoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatagoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatagoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatagoryView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatagoryDelete;
    private javax.swing.JButton btnCatagoryReset;
    private javax.swing.JButton btnCatagorySave;
    private javax.swing.JButton btnCatagoryUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblCatagoryView;
    private javax.swing.JTextField txtCatagoryId;
    private javax.swing.JTextField txtCatagoryName;
    // End of variables declaration//GEN-END:variables
}
